[[dfir]]
  name = "Incident Response"
  weight = 10
  identifier = "ir"
  url = "/dfir/ir/"

[[dfir]]
  name = "Malware"
  weight = 20
  identifier = "malware"
  url = "/dfir/malware/"

#[[dfir]]
#  name = "Techniques"
#  weight = 30
#  identifier = "techniques"
#  url = "/dfir/techniques/"

[[dfir]]
  name = "Forensics"
  weight = 40
  identifier = "forensics"
  url = "/dfir/forensics/"

[[dfir]]
  name = "Windows Event Logs"
  weight = 60
  identifier = "evtx"
  url = "/dfir/evtx/eventlogs/"

[[dfir]]
  name = "Guides"
  weight = 150
  identifier = "guides"
  url = "/dfir/guides/"

[[tools]]
  name = "DFIR Tools"
  weight = 10
  identifier = "dfir_tools"
  url = "/tools/dfir_tools/"

[[tools]]
  name = "Hardening & Mitigation Tools"
  weight = 20
  identifier = "hardening_mitigation_tools"
  url = "/tools/hardening_mitigation_tools/"

[[tools]]
  name = "Attacker Tools"
  weight = 30
  identifier = "attacker_tools"
  url = "/tools/attacker_tools/"

[[main]]
  name = "DFIR"
  url = "/dfir/ir/introduction"
  weight = 10

[[main]]
  name = "Tools"
  url = "/tools/attacker_tools/metasploit"
  weight = 20

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/Che4ter"
  post = "v0.1.0"
  weight = 20

#[[footer]]
#  name = "Privacy"
#  url = "/privacy-policy/"
#  weight = 10
